name: dash-build
on: 
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

  workflow_dispatch:

jobs:
  doc2dash:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: install doc2dash
        run: |
          brew install hynek/tap/doc2dash
          #brew install tree

      - name: clone gh-pages branch.
        run: |
          git clone https://github.com/WheheoHu/pybmd.git --branch gh-pages --single-branch gh-pages

      - name: Remove File
        uses: JesseTG/rm@v1.0.0
        with:
          path: ./gh-pages/dash_doc/pybmd.docset
        
      - name: doc2dash generate dash docset.
        run: |

          #tree 
          mkdir -p ./gh-pages/dash_doc/pybmd.docset
          doc2dash ./gh-pages -n pybmd -i ./docs/dash_docset_icon/icon@2x.png
          # -d ./gh-pages/dash_doc
          cp -R pybmd.docset ./gh-pages/dash_doc/pybmd.docset
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update dash docset" -a || true

         

      - name: upload dash doc as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dash_docset
          path: ./gh-pages/dash_doc/pybmd.docset
          
      - name: Remove File
        uses: JesseTG/rm@v1.0.0
        with:
          path: ./gh-pages/dash_doc

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     branch: gh-pages
      #     directory: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }} 
