name: sphinx-build

on:
  push:
    branches:    
      - master

  workflow_dispatch:
    
jobs:
  build_sphinx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    # - name: Set up Python
    #   run: uv python install

    - name: Install dependencies
      run: uv sync --extra docs

    - name: build sphinx docs
      run: |
        cd docs
        mkdir _static
        uv run sphinx-build -D todo_include_todos=0 . ./build/html/
        cd ..

    # - uses: wheheohu/sphinx-action@master
    #   with:
    #     docs-folder: "docs/"
        
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Clone ph-pages branch
      run: |
        git clone https://github.com/WheheoHu/pybmd.git --branch gh-pages --single-branch gh-pages
        rm -r ./gh-pages/*

    # - name: Remove File
    #   uses: JesseTG/rm@v1.0.0
    #   with:
    #     path: gh-pages/*

    - name: Commit documentation changes
      run: |
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    
    

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
  # doc2dash:
  #   needs: build_sphinx
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: install doc2dash
  #       run: |
  #         brew install hynek/tap/doc2dash
  #         brew install tree

  #     - name: clone gh-pages branch.
  #       run: |
  #         git clone https://github.com/WheheoHu/pybmd.git --branch gh-pages --single-branch gh-pages

  #     - name: Remove File
  #       uses: JesseTG/rm@v1.0.0
  #       with:
  #         path: ./gh-pages/dash_doc/pybmd.docset
        
  #     - name: doc2dash generate dash docset.
  #       run: |

  #         #tree 
  #         doc2dash ./gh-pages -n pybmd -i ./docs/dash_docset_icon/icon@2x.png
  #         # -d ./gh-pages/dash_doc
  #         cp -R pybmd.docset ./gh-pages/dash_doc/pybmd.docset
  #         cd gh-pages
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"
  #         git add .
  #         git commit -m "update dash docset" -a || true

         

  #     - name: upload dash doc as artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: dash_docset
  #         path: ./gh-pages/dash_doc/pybmd.docset
          
  #     - name: Remove File
  #       uses: JesseTG/rm@v1.0.0
  #       with:
  #         path: ./gh-pages/dash_doc/pybmd.docset

  #     - name: git subm
  #       run: |
  #         git submodule update --init
  #         # git rm --cached dash_doc/pybmd.docset/Contents/Resources/Documents

  #     - name: Push changes
  #       uses: ad-m/github-push-action@master
  #       with:
  #         branch: gh-pages
  #         directory: gh-pages
  #         github_token: ${{ secrets.GITHUB_TOKEN }} 